name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, xml, curl
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --prefer-dist --optimize-autoloader

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

          rsync -avz --exclude='storage/' --exclude='.env' --exclude='.git' --exclude='.github' ./ brad@half.black:/var/www/html/mydam

      - name: Set Permissions

        run: |
          ssh -o StrictHostKeyChecking=no brad@half.black "
            sudo chown -R brad:www-data /var/www/html/mydam &&
            sudo chmod -R 775 /var/www/html/mydam &&
            sudo chmod -R 775 /var/www/html/mydam/storage &&
            sudo chmod -R 775 /var/www/html/mydam/bootstrap/cache &&
            sudo chmod 664 /var/www/html/mydam/database/*.sqlite &&
            sudo chown brad:www-data /var/www/html/mydam/database/*.sqlite

      - name: Run Artisan commands
        run: |
          ssh -o StrictHostKeyChecking=no brad@half.black "cd /var/www/html/mydam && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
